# Generated by Django 4.2.3 on 2023-07-26 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
    

        migrations.AddField(
            model_name='seller',
            name='seller_slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, blank=True),
            preserve_default=False,
        ),

    ]
    