# Generated by Django 4.2.3 on 2023-07-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_seller_seller_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_slug',
        ),
    ]
