# Generated by Django 4.2.3 on 2023-07-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_seller_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
