# Generated by Django 3.1 on 2023-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=100, unique=True)),
                ('pin_code', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_image', models.ImageField(upload_to='userProfile')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'farmer'), (2, 'customer')], null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('Is_admin', models.BooleanField(default=False)),
                ('Is_active', models.BooleanField(default=False)),
                ('Is_staff', models.BooleanField(default=False)),
                ('Is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
