# Generated by Django 3.1 on 2023-07-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone_no',
            new_name='mobile_no',
        ),
    ]
