# Generated by Django 4.2.3 on 2023-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_contact_user_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='District',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
