# Generated by Django 3.1 on 2023-07-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20230709_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
