# Generated by Django 4.2.3 on 2023-07-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
