# Generated by Django 4.2.3 on 2023-08-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_openinghour'),
        ('orders', '0003_rename_items_orderedproduct_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='seller.seller'),
        ),
    ]
